sj-distributor/SmartTalk

src/SmartTalk.Api/Controllers/PhoneOrderController.cs, src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0002_add_phone_order_table.sql, src/SmartTalk.Core/Handlers/CommandHandlers/AddPhoneOrderConversationCommandHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/GetPhoneOrderConversationsRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/GetPhoneOrderOrderItemsRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/GetPhoneOrderRecordsRequestHandler.cs, src/SmartTalk.Core/Mappings/PhoneOrderMapping.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Conversation.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.OrderItem.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Conversation.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.cs, src/SmartTalk.IntegrationTests/Services/PhoneOrder/PhoneOrderFixture.cs, src/SmartTalk.IntegrationTests/TestBaseClasses/PhoneOrderFixtureBase.cs, src/SmartTalk.Messages/Commands/AddPhoneOrderConversationsCommand.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderConversationDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderOrderItemDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordDto.cs, src/SmartTalk.Messages/Requests/GetPhoneOrderConversationsRequest.cs, src/SmartTalk.Messages/Requests/GetPhoneOrderOrderItemsRequest.cs, src/SmartTalk.Messages/Requests/GetPhoneOrderRecordsRequest.cs
=> Add phone order interface

src/SmartTalk.Api/Controllers/PhoneOrderController.cs, src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0002_add_phone_order_table.sql, src/SmartTalk.Core/Handlers/CommandHandlers/PhoneOrder/AddPhoneOrderConversationCommandHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/PhoneOrder/GetPhoneOrderConversationsRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/PhoneOrder/GetPhoneOrderOrderItemsRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/PhoneOrder/GetPhoneOrderRecordsRequestHandler.cs, src/SmartTalk.Core/Mappings/UserAccountMapping.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Conversation.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/SmartTalk.Core.csproj, src/SmartTalk.IntegrationTests/Services/PhoneOrder/PhoneOrderFixture.cs, src/SmartTalk.Messages/Commands/PhoneOrder/AddPhoneOrderConversationsCommand.cs, src/SmartTalk.Messages/Requests/PhoneOrder/GetPhoneOrderConversationsRequest.cs, src/SmartTalk.Messages/Requests/PhoneOrder/GetPhoneOrderOrderItemsRequest.cs, src/SmartTalk.Messages/Requests/PhoneOrder/GetPhoneOrderRecordsRequest.cs, src/SmartTalk.Messages/SmartTalk.Messages.csproj
=> Adjust directory and add mapping

src/SmartTalk.Api/Authentication/Wiltechs/WiltechsAuthenticationHandler.cs, src/SmartTalk.Api/Authentication/Wiltechs/WiltechsAuthenticationOptions.cs, src/SmartTalk.Api/Authentication/Wiltechs/WiltechsUserInfo.cs, src/SmartTalk.Api/Extensions/AuthenticationExtension.cs, src/SmartTalk.Api/appsettings.json
=> Add oa and appsetting

src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0006_modify_user_account.sql
=> Fix user account table

src/SmartTalk.Core/Mappings/SecurityMapping.cs, src/SmartTalk.Core/Mappings/UserAccountMapping.cs
=> Fix user account mapping

src/SmartTalk.Messages/Dto/Speechmatics/SpeechmaticsJobConfigDto.cs, src/SmartTalk.Messages/Dto/Speechmatics/SpeechmaticsNotificationConfigDto.cs
=> Add notification config

src/SmartTalk.Core/Services/STT/SpeechToTextService.cs
=> Whisper auto recognize language

src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Services/Http/Clients/WeChatClient.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Add transcription filter parameter

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/Services/Embedding/ITextEmbeddingGenerator.cs, src/SmartTalk.Core/Services/Embedding/OpenaiTextEmbeddingGenerator.cs, src/SmartTalk.Core/Services/Http/Clients/SmartiesClient.cs, src/SmartTalk.Core/Services/VectorDb/IVectorDb.cs, src/SmartTalk.Core/Services/VectorDb/RedisVector.cs, src/SmartTalk.Core/Settings/Smarties/SmartiesSetting.cs, src/SmartTalk.Core/Settings/VectorDb/VectorDbSettings.cs, src/SmartTalk.Core/SmartTalk.Core.csproj, src/SmartTalk.Messages/Dto/OpenAi/OpenAiEmbeddingResponseDto.cs, src/SmartTalk.Messages/Dto/Smarties/AskGptEmbeddingDto.cs, src/SmartTalk.Messages/Dto/VectorDb/RetrievalFilterDto.cs, src/SmartTalk.Messages/Enums/OpenAi/OpenAiEmbeddingModel.cs
=> Add redis searching

src/SmartTalk.Core/Domain/Restaurants/Restaurant.cs, src/SmartTalk.Core/Domain/Restaurants/RestaurantMenuItem.cs, src/SmartTalk.Core/Handlers/CommandHandlers/Restaurant/SchedulingSyncRestaurantMenuCommandHandler.cs, src/SmartTalk.Core/Jobs/RecurringJobs/SchedulingSyncRestaurantMenuRecurringJob.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantDataProvider.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs, src/SmartTalk.Messages/Commands/Restaurants/SchedulingSyncRestaurantMenuCommand.cs
=> Add recurring job to sync the restaurant menu

src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0010_add_restaurant_menu_item_table.sql, src/SmartTalk.Core/Domain/Restaurants/RestaurantMenuItem.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs, src/SmartTalk.Messages/Dto/Restaurant/RestaurantMenuItemDto.cs, src/SmartTalk.Messages/Enums/Restaurants/RestaurantItemLanguage.cs
=> Optimize restaurant table

src/SmartTalk.Core/Constants/HangfireConstants.cs, src/SmartTalk.Core/Mappings/RestaurantMapping.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantDataProvider.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs, src/SmartTalk.Messages/Constants/VectorDbStore.cs, src/SmartTalk.Messages/Dto/Restaurant/RestaurantPayloadDto.cs
=> Persist restaurant menu item to vector

src/SmartTalk.Api/Controllers/RestaurantController.cs, src/SmartTalk.Core/Handlers/CommandHandlers/Restaurant/AddRestaurantCommandHandler.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantDataProvider.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantService.cs, src/SmartTalk.IntegrationTests/Services/Restaurants/RestaurantFixture.cs, src/SmartTalk.IntegrationTests/TestBaseClasses/RestaurantFixtureBase.cs, src/SmartTalk.Messages/Commands/Restaurants/AddRestaurantCommand.cs
=> Expose add restaurant api

src/SmartTalk.Api/Extensions/AuthenticationExtension.cs
=> Add token validation

src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs
=> Adjust sync restaurant menu

src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderConversationDto.cs
=> Modify add conversation

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Messages/Requests/PhoneOrder/GetPhoneOrderOrderItemsRequest.cs
=> Add phone order record tips

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Add check restaurant recording role

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Modify receive phone order record

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Messages/Dto/EasyPos/GetOrderResponseDto.cs
=> Fix manual order

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> modify get pos

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Modify record create time

src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0014_modify_phone_order_conversation.sql
=> Modify phone order conversation answer

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Modify transcription text

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0014_add_speech_matics_tabel.sql, src/SmartTalk.Core/Domain/SpeechMatics/SpeechMaticsKey.cs, src/SmartTalk.Core/Handlers/CommandHandlers/SpeechMatics/SchedulingUpdateSpeechMaticsKeysCommandHandler.cs, src/SmartTalk.Core/Jobs/RecurringJobs/SchedulingUpdateSpeechMaticsKeysRecurringJob.cs, src/SmartTalk.Core/Services/Http/Clients/SpeechMaticsClient.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.cs, src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsDataProvider.cs, src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsJobService.cs, src/SmartTalk.Core/Settings/SpeechMatics/SpeechMaticsKeySetting.cs, src/SmartTalk.Messages/Commands/SpeechMatics/SchedulingUpdateSpeechMaticsKeysCommand.cs, src/SmartTalk.Messages/Enums/SpeechMatics/SpeechMaticsKeyStatus.cs
=> Add speech matics key auto switch

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Add restaurant phone

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Send.cs
=> Modify data broad cast job

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Send.cs
=> Modify data broad cast

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Send.cs, src/SmartTalk.Core/Settings/PhoneOrder/SchedulingPhoneOrderDailyDataBroadcastRecurringJobExpressionSetting.cs, src/SmartTalk.Messages/Commands/PhoneOrder/SchedulingPhoneOrderDailyDataBroadcastCommand.cs
=> Modify data broadcast

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Conversation.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderUtilService.cs, src/SmartTalk.IntegrationTests/Services/PhoneOrder/PhoneOrderFixture.cs, src/SmartTalk.IntegrationTests/appsettings.json, src/SmartTalk.Messages/Commands/PhoneOrder/AddPhoneOrderConversationsCommand.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderConversationDto.cs
=> Get order detail after add converastion

src/SmartTalk.Api/Controllers/PhoneOrderController.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsService.cs, src/SmartTalk.IntegrationTests/Services/Security/SecurityFixture.cs, src/SmartTalk.Messages/Commands/PhoneOrder/ReceivePhoneOrderRecordCommand.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordInformationDto.cs, src/SmartTalk.Messages/Enums/PhoneOrder/PhoneOrderRestaurant.cs
=> Add restaurant

src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs, src/SmartTalk.Messages/Dto/EasyPos/EasyPosResponseDto.cs
=> fix dish to zero

src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0019_modify_phone_order_record_table.sql, src/SmartTalk.Core/DbUpFile/Scripts_2024/Script0020_modify_phone_order_record_last_modified_by_name_field.sql, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Conversation.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Optimize phone order query

src/SmartTalk.Core/Constants/AliyunConstants.cs, src/SmartTalk.Core/Services/Http/Clients/AlidnsClient.cs, src/SmartTalk.Core/SmartTalk.Core.csproj
=> Add aliyun update domain record 

src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs, src/SmartTalk.Messages/Dto/EasyPos/EasyPosResponseDto.cs
=> Fix easypos response

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add call number and current time

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add user info and order item function call

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add order repeat and place function

src/SmartTalk.Api/Extensions/HangfireExtension.cs
=> Add sip hangfire server

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0002_modify_ai_speech_assistant_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add big model realtime api

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0003_add_cloumn_for_ai_speech_assistant.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Core/Settings/ZhiPuAi/ZhiPuAiSettings.cs, src/SmartTalk.Messages/Constants/AiSpeechAssistantStore.cs, src/SmartTalk.Messages/Enums/AiSpeechAssistant/AiSpeechAssistantProvider.cs
=> Enhance llm realtime api

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/Services/Http/Clients/EasyPosClient.cs, src/SmartTalk.Core/Settings/EasyPos/EasyPosSetting.cs, src/SmartTalk.Messages/Dto/EasyPos/PlaceOrderToEasyPosRequestDto.cs
=> Add method to place order to pos

src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordDto.cs
=> Update optimize phone order query

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/Constants/OpenAiToolConstants.cs, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0004_add_ai_speech_assistant_human_contact.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistantHumanContact.cs, src/SmartTalk.Core/Handlers/CommandHandlers/AiSpeechAssistant/TransferHumanServiceCommandHandler.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Core/Settings/Twilio/TwilioSettings.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/TransferHumanServiceCommand.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantStreamContxtDto.cs
=> Ai phone order transfer call

src/SmartTalk.Core/Constants/OpenAiToolConstants.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Ai phone transfer scenario

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0007_modify_phone_order_table.sql, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Domain/Restaurants/Restaurant.cs, src/SmartTalk.Core/Services/Agents/AgentDataProvider.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Conversation.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Send.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderUtilService.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantDataProvider.cs, src/SmartTalk.IntegrationTests/Services/PhoneOrder/PhoneOrderFixture.cs, src/SmartTalk.Messages/Dto/Agent/AgentDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/GetPhoneOrderRecordsForRestaurantCountDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordInformationDto.cs, src/SmartTalk.Messages/Requests/PhoneOrder/GetPhoneOrderRecordsRequest.cs
=> Adjust logic about restaurant

src/SmartTalk.Api/Controllers/AgentController.cs, src/SmartTalk.Core/Handlers/RequestHandlers/Agent/GetAgentsRequestHandler.cs, src/SmartTalk.Core/Services/Agents/AgentDataProvider.cs, src/SmartTalk.Core/Services/Agents/AgentService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantDataProvider.cs, src/SmartTalk.Messages/Requests/Agent/GetAgentsRequest.cs, src/SmartTalk.Messages/Requests/PhoneOrder/GetPhoneOrderRecordsRequest.cs
=> Add api for getting agents

src/SmartTalk.Api/Controllers/PhoneOrderController.cs, src/SmartTalk.Api/Controllers/RestaurantController.cs, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script00010_modify_phone_order_item_table.sql, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script00011_modify_restauran_menu_item_table.sql, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script00012_update_phone_order_record_table.sql, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderOrderItem.cs, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Domain/Restaurants/RestaurantMenuItem.cs, src/SmartTalk.Core/Handlers/CommandHandlers/PhoneOrder/PlaceOrderAndModifyItemCommandHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/Restaurant/GetRestaurantMenuItemsRequestHandler.cs, src/SmartTalk.Core/Mappings/AgentMapping.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderUtilService.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantDataProvider.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantProcessJobService.cs, src/SmartTalk.Core/Services/Restaurants/RestaurantService.cs, src/SmartTalk.Messages/Commands/PhoneOrder/PlaceOrderAndModifyItemCommand.cs, src/SmartTalk.Messages/Dto/EasyPos/PlaceOrderToEasyPosRequestDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderOrderItemDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderOrderItemModifiers.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordDto.cs, src/SmartTalk.Messages/Dto/Restaurant/RestaurantMenuItemDto.cs, src/SmartTalk.Messages/Dto/Restaurant/RestaurantPayloadDto.cs, src/SmartTalk.Messages/Dto/WebSocket/PhoneOrderDetailDto.cs, src/SmartTalk.Messages/Enums/PhoneOrder/PhoneOrderOrderStatus.cs, src/SmartTalk.Messages/Requests/Restaurant/GetRestaurantItemRequest.cs
=> Add api to place order and get menu

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Messages/Dto/EasyPos/PlaceOrderToEasyPosRequestDto.cs
=> Enhance easy pos order place

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script00014_modify_ai_speech_assistant_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantDto.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantStreamContxtDto.cs
=> Add ai assistant greetings

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Update phone record created time

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script00015_add_ai_speech_assistant_function_call_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistantFunctionCall.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Persist function call and initial

src/SmartTalk.Core/Constants/OpenAiToolConstants.cs, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script00014_add_order_comment_for_phone_order_record_table.sql, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantProcessJobService.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.OrderItem.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantStreamContxtDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordDto.cs
=> Enhance order info setting

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> Fix recieve get agent

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Fix realtime websocket event bug

src/SmartTalk.Api/Controllers/AiSpeechAssistantController.cs, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistantKnowledge.cs, src/SmartTalk.Core/Handlers/CommandHandlers/AiSpeechAssistant/AddAiSpeechAssistantKnowledgeCommandHandler.cs, src/SmartTalk.Core/Handlers/CommandHandlers/AiSpeechAssistant/UpdateAiSpeechAssistantKnowledgeCommandHandler.cs, src/SmartTalk.Core/Handlers/EventHandlers/AiSpeechAssistant/AiSpeechAssistantKnowledgeAddedEventHandler.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs, src/SmartTalk.Core/Services/EventHandling/EventHandlingService.AiSpeechAssistant.cs, src/SmartTalk.Core/Services/EventHandling/EventHandlingService.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/UpdateAiSpeechAssistantKnowledgeCommand.cs, src/SmartTalk.Messages/Events/AiSpeechAssistant/AiSpeechAssistantKnowledgeAddedEvent.cs
=> Add brief for knowledge change

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0026_add_channel_for_ai_speech_assistant_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.Query.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/AddAiSpeechAssistantCommand.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/UpdateAiSpeechAssistantCommand.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantDto.cs, src/SmartTalk.Messages/Enums/AiSpeechAssistant/AiSpeechAssistantChannel.cs, src/SmartTalk.Messages/Requests/AiSpeechAssistant/GetAiSpeechAssistantsRequest.cs
=> Add channel for assistant

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.Realtime.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Fix extra webscoket client

src/SmartTalk.Core/Services/EventHandling/EventHandlingService.AiSpeechAssistant.cs
=> Fix brief generate null pointer

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Core/Settings/Azure/AzureSetting.cs
=> Add azure realtime

src/SmartTalk.Api/Controllers/VoiceAiController.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/CreatePosCompanyStoreCommandHandler.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/DeletePosCompanyStoreCommandHandler.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/UpdatePosCompanyStoreCommandHandler.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/UpdatePosCompanyStoreStatusCommandHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GePosCompanyStoreDetailRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GetPosCompanyWithStoresRequestHandler.cs, src/SmartTalk.Core/Mappings/VoiceAiMapping.cs, src/SmartTalk.Core/Services/VoiceAi/PosManagement/PosManagementDataProvider.cs, src/SmartTalk.Core/Services/VoiceAi/PosManagement/PosManagementService.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/CreatePosCompanyStoreCommand.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/DeletePosCompanyStoreCommand.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/UpdatePosCompanyStoreCommand.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/UpdatePosCompanyStoreStatusCommand.cs, src/SmartTalk.Messages/Dto/VoiceAi/PosManagement/PosCompanyDto.cs, src/SmartTalk.Messages/Dto/VoiceAi/PosManagement/PosCompanyStoreDto.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosCompanyStoreDetailRequest.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosCompanyWithStoresRequest.cs
=> Add pos company stores apis

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add call from number

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs
=> Fix assistant channel initialization

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0030_add_agent_message_record_table.sql, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0031_add_is_wecom_message_order_to_agent_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AgentMessageRecord.cs, src/SmartTalk.Core/Domain/System/Agent.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add agent message record number

src/SmartTalk.Core/Services/RealtimeAi/Adapters/WebSocketClientExtensions.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/OpenAi/OpenAiRealtimeAiWssClient.cs, src/SmartTalk.Core/SmartTalk.Core.csproj
=> Add websocket client

src/SmartTalk.Core/Services/RealtimeAi/Wss/OpenAi/OpenAiRealtimeAiWssClient.cs
=> Adjust openai realtime ai client

src/SmartTalk.Core/Services/RealtimeAi/Services/RealtimeAiService.cs, src/SmartTalk.Core/Services/RealtimeAi/Services/TwilioUtilService.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/IRealtimeAiConversationEngine.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/IRealtimeAiProviderAdapter.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/OpenAi/OpenAiRealtimeAiAdapter.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/OpenAi/OpenAiRealtimeAiWssClient.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/RealtimeAiConversationEngine.cs, src/SmartTalk.Messages/Enums/RealtimeAi/RealtimeAiAudioCodec.cs
=> Optimize realtime ai logic

src/SmartTalk.Api/Controllers/RealtimeAiController.cs, src/SmartTalk.Core/Handlers/CommandHandlers/RealtimeAi/RealtimeAiConnectCommandHandler.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/RealtimeAi/Services/RealtimeAiService.cs, src/SmartTalk.Messages/Commands/RealtimeAi/RealtimeAiConnectCommand.cs
=> Add controller and api for realtime ai

src/SmartTalk.Core/Domain/AISpeechAssistant/AgentMessageRecord.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Fix agent message record logic

src/SmartTalk.Api/Controllers/VoiceAiController.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/UpdatePosCategoryCommandHandler.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/UpdatePosMenuCommandHandler.cs, src/SmartTalk.Core/Handlers/CommandHandlers/VoiceAi/PosManagement/UpdatePosProductCommandHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GetPosCategoryRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GetPosMenuDetailRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GetPosMenuPreviewRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GetPosMenusListRequestHandler.cs, src/SmartTalk.Core/Handlers/RequestHandlers/VoiceAi/PosManagement/GetPosProductRequestHandler.cs, src/SmartTalk.Core/Mappings/VoiceAiMapping.cs, src/SmartTalk.Core/Services/VoiceAi/PosManagement/PosManagementDataProvider.Company.cs, src/SmartTalk.Core/Services/VoiceAi/PosManagement/PosManagementService.Company.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/UpdatePosCategoryCommand.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/UpdatePosMenuCommand.cs, src/SmartTalk.Messages/Commands/VoiceAi/PosManagement/UpdatePosProductCommand.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosCategoryRequest.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosMenuDetailRequest.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosMenuPreviewRequest.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosMenuPrviewRequest.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosMenusListRequest.cs, src/SmartTalk.Messages/Requests/VoiceAi/PosManagement/GetPosProductRequest.cs
=> Voice ai pos 0.7 menu preview

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0033_add_ai_kid_table.sql, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0034_add_is_display_for_ai_assistant_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiKid.cs, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/AddAiSpeechAssistantCommand.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/UpdateAiSpeechAssistantKnowledgeCommand.cs, src/SmartTalk.Messages/Dto/Agent/AgentType.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantDto.cs, src/SmartTalk.Messages/Enums/AiSpeechAssistant/AiKidVoiceType.cs
=> Adjust assistant for ai kid

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0033_updtae_agent_column.sql, src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0035_updtae_agent_and_add_pos_agent_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Domain/IAgent.cs, src/SmartTalk.Core/Domain/Pos/PosAgent.cs, src/SmartTalk.Core/Domain/Pos/PosCompanyStore.cs, src/SmartTalk.Core/Domain/Restaurants/Restaurant.cs, src/SmartTalk.Core/Domain/System/Agent.cs, src/SmartTalk.Core/Services/Agents/AgentDataProvider.cs, src/SmartTalk.Core/Services/Agents/AgentService.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs, src/SmartTalk.Core/Services/Pos/PosDataProvider.cs, src/SmartTalk.Core/Services/Pos/PosService.cs, src/SmartTalk.Messages/Commands/AiSpeechAssistant/AddAiSpeechAssistantCommand.cs, src/SmartTalk.Messages/Dto/Agent/AgentDto.cs, src/SmartTalk.Messages/Dto/Agent/AgentPreviewDto.cs, src/SmartTalk.Messages/Requests/Agent/GetAgentsRequest.cs
=> Optimize agent related logic

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.AssistantCustom.cs, src/SmartTalk.Messages/Constants/AiSpeechAssistantStore.cs
=> Change ai kid voice

src/SmartTalk.Api/Controllers/PosController.cs, src/SmartTalk.Core/Handlers/CommandHandlers/Pos/AdjustPosMenuContentSortCommandHandler.cs, src/SmartTalk.Core/Services/Pos/PosDataProvider.Company.cs, src/SmartTalk.Core/Services/Pos/PosService.Company.cs, src/SmartTalk.Messages/Commands/Pos/AdjustPosMenuContentSortCommand.cs, src/SmartTalk.Messages/Enums/Pos/PosMenuContentType.cs
=> Adjust menu content sort

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0035_add_group_key.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AgentMessageRecord.cs, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistant.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add group key sorting

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/Http/Clients/SmartiesClient.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderUtilService.cs, src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsService.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiKidCallBackRequestDto.cs
=> Handle smarties ai kid recording

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderUtilService.cs
=> Fix get restaurant null pointer

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderDataProvider.Record.cs
=> Distinct phone order record

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsService.cs
=> Hot fix assistant null pointer when handle transcription

src/SmartTalk.Messages/Constants/AiSpeechAssistantStore.cs
=> Adjust realtime default url

src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/Services/Http/Clients/SalesClient.cs, src/SmartTalk.Core/Settings/Sales/SalesSetting.cs, src/SmartTalk.Messages/Dto/Sales/GenerateAiOrdersRequestDto.cs, src/SmartTalk.Messages/Dto/Sales/GetAskInfoDetailListByCustomerRequestDto.cs, src/SmartTalk.Messages/Dto/Sales/GetOrderHistoryByCustomerRequestDto.cs, src/SmartTalk.Messages/Dto/Sales/SalesResponseDto.cs
=> Add sales order relate api

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0038_add_sales_table.sql, src/SmartTalk.Core/Domain/Sales/Sales.cs, src/SmartTalk.Messages/Dto/Sales/SalesDto.cs, src/SmartTalk.Messages/Enums/Sales/SalesCallType.cs
=> Add sales table

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.Query.cs, src/SmartTalk.Messages/Requests/AiSpeechAssistant/GetAiSpeechAssistantsRequest.cs
=> Add assistant fuzzy query

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderProcessJobService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsService.cs
=> Calculate recording duration

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0040_add_column_mark_phone_order_record_is_transfer.sql, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantProcessJobService.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Messages/Dto/AiSpeechAssistant/AiSpeechAssistantStreamContxtDto.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneOrderRecordDto.cs
=> Call record mark transfer

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Hot fix language detect

src/SmartTalk.Core/Services/Pos/PosDataProvider.Company.cs, src/SmartTalk.Core/Services/Pos/PosService.Company.cs
=> Filter invalid pos categories

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0048_add_incoming_number_for_phone_record.sql, src/SmartTalk.Core/Domain/PhoneOrder/PhoneOrderRecord.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantProcessJobService.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderProcessJobService.cs, src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs, src/SmartTalk.Messages/Dto/PhoneOrder/PhoneCallRecorddetailDto.cs
=> Hot fix record detail export

src/SmartTalk.Core/Handlers/CommandHandlers/AiSpeechAssistant/ReceivePhoneRecordingStatusCallbackCommandHandler.cs
=> Optimize twilio recording callback

src/SmartTalk.Core/DbUpFile/Scripts_2025/Script0037_add_assistant_number_match_table.sql, src/SmartTalk.Core/Domain/AISpeechAssistant/AiSpeechAssistantInboundRoute.cs, src/SmartTalk.Core/Domain/AISpeechAssistant/AssistantNumberMatch.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantDataProvider.cs, src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add assistant number inbound route

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Hot fix transfer no delay

src/SmartTalk.Core/Services/SpeechMatics/SpeechMaticsService.cs
=> Fix transcription empty result

src/SmartTalk.Messages/Constants/AiSpeechAssistantStore.cs
=> Adjust ai speech default model

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Add twilio websocket retry

src/SmartTalk.Core/Services/PhoneOrder/PhoneOrderService.Record.cs
=> hot-fix-smart-talk-get-record-report

src/SmartTalk.Api/Controllers/RealtimeAiController.cs, src/SmartTalk.Api/appsettings.json, src/SmartTalk.Core/Services/RealtimeAi/Services/RealtimeAiService.cs, src/SmartTalk.Core/Services/RealtimeAi/Services/TwilioUtilService.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/Google/GoogleRealtimeAiAdapter.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/IRealtimeAiConversationEngine.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/IRealtimeAiProviderAdapter.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/OpenAi/OpenAiRealtimeAiAdapter.cs, src/SmartTalk.Core/Services/RealtimeAi/Wss/RealtimeAiConversationEngine.cs, src/SmartTalk.Core/Settings/OpenAi/OpenAiSettings.cs, src/SmartTalk.Messages/Commands/RealtimeAi/RealtimeAiConnectCommand.cs, src/SmartTalk.Messages/Enums/RealtimeAi/RealtimeAiServerRegion.cs
=> Add region tag for realtime connect

src/SmartTalk.Core/Services/AiSpeechAssistant/AiSpeechAssistantService.cs
=> Fix repeat order prompt
